### ISSUE TITLE
[Exploit/Bug] Execute javascript

### ISSUE THREAD

**Issue by rusprice** [FriendsOfFlarum/socialprofile#8]
On your profile, you can execute JavaScript when somebody clicks one of your social links. if you added a social link with any name and have the URL be "javascript:{yourjscodehere]" then that JS will execute when somebody clicks on that link. Luckily, this javascript will not execute on the forum but rather a new page and because no page was specified, most browsers will execute it in about:blank.

**Comment by clarkwinkelmann** [comment]
Thanks for the report! We will investigate and prepare a fix.

I would have expected the `url` validation rule to prevent that, but I suppose that's actually not the case.

**Comment by Ralkage** [comment]
Hi there 👋 not sure which version this was fixed in, but the url validation rule is working again

![image](https://user-images.githubusercontent.com/2059356/111715593-8f5a5d00-882a-11eb-84a6-6218887c31f4.png)

Please let us know if the issue persists for you on the latest version @UntrustableRus  and feel free to create a new issue if it does.

**Comment by dsevillamartin** [comment]
Reopening because the wrong code was tested (`<script>` tag instead of `javascript:...` url).

**Comment by dsevillamartin** [comment]
Looks like it has been fixed at some point. The URL validation prevents it from being saved with `javascript:`.
